resolver: lts-12.2
packages:
  - '.'
extra-deps:
  - base-orphans-0.8
  - generic-data-0.3.0.0
  - tree-diff-0.0.2
  - git: https://github.com/stevana/quickcheck.git
    commit: 238af2d190765e77b0944361c9dc58432ae26ecb
  - git: https://github.com/advancedtelematic/markov-chain-usage-model.git
    commit: 61cca4250667289be310f8a76fe317acc62a3cb6
  # - ../markov-chain-usage-model
nix:
  enable: false
  pure: false
  packages: [
    blas
    gfortran.cc
    glpk
    gsl
    haskellPackages.tasty-discover
    liblapack
    sundials
    zlib
    ]

allow-newer: true
